
import { MutualFund } from './types';

export const MOCK_FUNDS: MutualFund[] = [
  {
    id: '1',
    schemeCode: '120847',
    name: 'Quant Small Cap Fund - Growth',
    category: 'Small Cap',
    risk: 'High',
    expenseRatio: 0.77,
    exitLoad: '1% if redeemed within 1 year',
    aum: '₹17,400 Cr',
    aumValue: 17400,
    benchmarkName: 'Nifty Smallcap 250 TRI',
    returns: { '1y': 52.4, '3y': 38.2, '5y': 32.1, '10y': 24.5, 'rolling': 28.5 },
    benchmarkReturns: { '5y': 22.1 },
    manager: { name: 'Ankit Pande', experience: 12, rating: 4.8, tenureYears: 4 },
    holdings: ['Reliance Industries', 'Jio Financial', 'HDFC Bank'],
    riskRatios: { sharpe: 1.85, alpha: 8.2, beta: 1.15, sortino: 2.1, standardDeviation: 18.5 },
    score: { total: 92, returns: 28, expense: 12, manager: 14, volatility: 11, aum: 9, drawdown: 13, quality: 5 },
    description: 'Extremely aggressive fund using predictive analytics to capture momentum.',
    redFlags: []
  },
  {
    id: '2',
    schemeCode: '119598',
    name: 'Parag Parikh Flexi Cap Fund - Direct',
    category: 'Flexi Cap',
    risk: 'Medium',
    expenseRatio: 0.61,
    exitLoad: '2% < 1yr, 1% < 2yrs',
    aum: '₹58,200 Cr',
    aumValue: 58200,
    benchmarkName: 'Nifty 500 TRI',
    returns: { '1y': 32.1, '3y': 22.4, '5y': 24.8, '10y': 19.8, 'rolling': 21.2 },
    benchmarkReturns: { '5y': 18.4 },
    manager: { name: 'Rajeev Thakkar', experience: 22, rating: 4.9, tenureYears: 11 },
    holdings: ['Alphabet Inc', 'ITC Ltd', 'Bajaj Holdings'],
    riskRatios: { sharpe: 1.45, alpha: 5.1, beta: 0.78, sortino: 1.9, standardDeviation: 12.4 },
    score: { total: 95, returns: 29, expense: 14, manager: 15, volatility: 14, aum: 10, drawdown: 9, quality: 4 },
    description: 'Value-oriented fund with international exposure and conservative approach.',
    redFlags: []
  },
  {
    id: '3',
    schemeCode: '143467',
    name: 'Nippon India Nifty 50 Index Fund',
    category: 'Index Fund',
    risk: 'Low',
    expenseRatio: 0.15,
    exitLoad: 'Nil',
    aum: '₹3,200 Cr',
    aumValue: 3200,
    benchmarkName: 'Nifty 50 TRI',
    returns: { '1y': 21.2, '3y': 15.4, '5y': 14.1, '10y': 13.2, 'rolling': 13.8 },
    benchmarkReturns: { '5y': 14.1 },
    manager: { name: 'Himanshu Mange', experience: 8, rating: 4.2, tenureYears: 3 },
    holdings: ['HDFC Bank', 'Reliance', 'ICICI Bank', 'Infosys'],
    riskRatios: { sharpe: 0.95, alpha: -0.05, beta: 1.0, sortino: 1.1, standardDeviation: 14.1 },
    score: { total: 88, returns: 20, expense: 15, manager: 12, volatility: 15, aum: 8, drawdown: 13, quality: 5 },
    description: 'Low-cost tracker for Nifty 50, perfect for long-term core portfolios.',
    redFlags: []
  },
  {
    id: '4',
    schemeCode: '103175',
    name: 'SBI Bluechip Fund - Direct Growth',
    category: 'Large Cap',
    risk: 'Medium',
    expenseRatio: 0.85,
    exitLoad: '1% if redeemed within 1 year',
    aum: '₹42,000 Cr',
    aumValue: 42000,
    benchmarkName: 'S&P BSE 100 TRI',
    returns: { '1y': 25.4, '3y': 18.2, '5y': 15.1, '10y': 14.5, 'rolling': 16.5 },
    benchmarkReturns: { '5y': 14.1 },
    manager: { name: 'Sohini Andani', experience: 18, rating: 4.5, tenureYears: 10 },
    holdings: ['HDFC Bank', 'ICICI Bank', 'Larsen & Toubro'],
    riskRatios: { sharpe: 1.15, alpha: 1.2, beta: 0.95, sortino: 1.4, standardDeviation: 13.5 },
    score: { total: 85, returns: 22, expense: 12, manager: 14, volatility: 13, aum: 10, drawdown: 9, quality: 5 },
    description: 'Steady large-cap performer focusing on market leaders.',
    redFlags: []
  },
  {
    id: '5',
    schemeCode: '102000',
    name: 'HDFC Mid-Cap Opportunities - Direct',
    category: 'Mid Cap',
    risk: 'High',
    expenseRatio: 0.72,
    exitLoad: '1% if redeemed within 1 year',
    aum: '₹65,000 Cr',
    aumValue: 65000,
    benchmarkName: 'Nifty Midcap 150 TRI',
    returns: { '1y': 44.4, '3y': 28.2, '5y': 22.1, '10y': 19.5, 'rolling': 20.5 },
    benchmarkReturns: { '5y': 18.1 },
    manager: { name: 'Chirag Setalvad', experience: 20, rating: 4.8, tenureYears: 15 },
    holdings: ['The Indian Hotels', 'Tata Communications', 'Apollo Tyres'],
    riskRatios: { sharpe: 1.55, alpha: 4.2, beta: 1.05, sortino: 1.8, standardDeviation: 16.5 },
    score: { total: 91, returns: 27, expense: 13, manager: 15, volatility: 11, aum: 10, drawdown: 10, quality: 5 },
    description: 'One of the largest mid-cap funds with a track record of identifying winners early.',
    redFlags: []
  },
  {
    id: '6',
    schemeCode: '119841',
    name: 'Axis Small Cap Fund - Direct',
    category: 'Small Cap',
    risk: 'High',
    expenseRatio: 0.55,
    exitLoad: '1% if redeemed within 1 year',
    aum: '₹20,000 Cr',
    aumValue: 20000,
    benchmarkName: 'Nifty Smallcap 250 TRI',
    returns: { '1y': 38.4, '3y': 25.2, '5y': 28.1, '10y': 22.5, 'rolling': 24.5 },
    benchmarkReturns: { '5y': 22.1 },
    manager: { name: 'Mayank Hyanki', experience: 15, rating: 4.6, tenureYears: 5 },
    holdings: ['Cholamandalam', 'Birlasoft', 'Fine Organic'],
    riskRatios: { sharpe: 1.65, alpha: 6.2, beta: 0.85, sortino: 2.0, standardDeviation: 14.5 },
    score: { total: 93, returns: 28, expense: 15, manager: 13, volatility: 14, aum: 9, drawdown: 9, quality: 5 },
    description: 'Quality-focused small cap fund that prioritizes downside protection.',
    redFlags: []
  },
  {
    id: '7',
    schemeCode: '102865',
    name: 'Mirae Asset Large Cap Fund - Direct',
    category: 'Large Cap',
    risk: 'Medium',
    expenseRatio: 0.52,
    exitLoad: 'Nil',
    aum: '₹37,000 Cr',
    aumValue: 37000,
    benchmarkName: 'Nifty 100 TRI',
    returns: { '1y': 26.4, '3y': 17.2, '5y': 16.1, '10y': 15.5, 'rolling': 17.5 },
    benchmarkReturns: { '5y': 15.1 },
    manager: { name: 'Gaurav Misra', experience: 25, rating: 4.4, tenureYears: 6 },
    holdings: ['HDFC Bank', 'ICICI Bank', 'Reliance'],
    riskRatios: { sharpe: 1.25, alpha: 1.5, beta: 0.98, sortino: 1.6, standardDeviation: 13.0 },
    score: { total: 89, returns: 23, expense: 15, manager: 14, volatility: 14, aum: 9, drawdown: 9, quality: 5 },
    description: 'Consistent performer in the large-cap space with a growth at reasonable price approach.',
    redFlags: []
  },
  {
    id: '8',
    schemeCode: '118991',
    name: 'ICICI Prudential Bluechip - Direct',
    category: 'Large Cap',
    risk: 'Medium',
    expenseRatio: 0.91,
    exitLoad: '1% if redeemed within 1 year',
    aum: '₹52,000 Cr',
    aumValue: 52000,
    benchmarkName: 'Nifty 100 TRI',
    returns: { '1y': 29.4, '3y': 19.2, '5y': 17.1, '10y': 14.5, 'rolling': 18.5 },
    benchmarkReturns: { '5y': 15.1 },
    manager: { name: 'Anish Tawakley', experience: 22, rating: 4.7, tenureYears: 8 },
    holdings: ['ICICI Bank', 'Infosys', 'Axis Bank'],
    riskRatios: { sharpe: 1.35, alpha: 2.5, beta: 0.92, sortino: 1.7, standardDeviation: 12.5 },
    score: { total: 90, returns: 25, expense: 11, manager: 15, volatility: 15, aum: 10, drawdown: 9, quality: 5 },
    description: 'Focuses on the top 100 companies by market cap with a value-tilted approach.',
    redFlags: []
  },
  {
    id: '9',
    schemeCode: '120166',
    name: 'Kotak Emerging Equity - Direct',
    category: 'Mid Cap',
    risk: 'High',
    expenseRatio: 0.44,
    exitLoad: '1% if redeemed within 1 year',
    aum: '₹40,000 Cr',
    aumValue: 40000,
    benchmarkName: 'Nifty Midcap 150 TRI',
    returns: { '1y': 41.4, '3y': 26.2, '5y': 21.1, '10y': 20.5, 'rolling': 21.5 },
    benchmarkReturns: { '5y': 18.1 },
    manager: { name: 'Harsha Upadhyaya', experience: 21, rating: 4.9, tenureYears: 12 },
    holdings: ['Supreme Industries', 'Cummins India', 'Schaeffler India'],
    riskRatios: { sharpe: 1.45, alpha: 3.5, beta: 0.88, sortino: 1.8, standardDeviation: 14.0 },
    score: { total: 94, returns: 26, expense: 15, manager: 15, volatility: 14, aum: 10, drawdown: 9, quality: 5 },
    description: 'A mid-cap giant known for low turnover and long-term conviction bets.',
    redFlags: []
  },
  {
    id: '10',
    schemeCode: '120516',
    name: 'Tata Digital India Fund - Direct',
    category: 'Sectoral',
    risk: 'High',
    expenseRatio: 0.35,
    exitLoad: '0.25% if redeemed within 30 days',
    aum: '₹9,000 Cr',
    aumValue: 9000,
    benchmarkName: 'Nifty IT TRI',
    returns: { '1y': 22.4, '3y': 12.2, '5y': 25.1, '10y': 18.5, 'rolling': 19.5 },
    benchmarkReturns: { '5y': 23.1 },
    manager: { name: 'Meeta Shetty', experience: 14, rating: 4.3, tenureYears: 4 },
    holdings: ['TCS', 'Infosys', 'HCL Tech'],
    riskRatios: { sharpe: 1.05, alpha: 1.5, beta: 1.12, sortino: 1.2, standardDeviation: 22.5 },
    score: { total: 82, returns: 24, expense: 15, manager: 12, volatility: 8, aum: 8, drawdown: 10, quality: 5 },
    description: 'Concentrated exposure to the Indian IT sector and digital services.',
    redFlags: []
  },
  {
    id: '11',
    schemeCode: '120823',
    name: 'Quant Active Fund - Direct Growth',
    category: 'Multi Cap',
    risk: 'High',
    expenseRatio: 0.75,
    exitLoad: '1% if redeemed within 15 days',
    aum: '₹10,000 Cr',
    aumValue: 10000,
    benchmarkName: 'Nifty 500 Multicap 50:25:25 TRI',
    returns: { '1y': 48.4, '3y': 32.2, '5y': 30.1, '10y': 23.5, 'rolling': 26.5 },
    benchmarkReturns: { '5y': 20.1 },
    manager: { name: 'Sanjeev Sharma', experience: 16, rating: 4.7, tenureYears: 5 },
    holdings: ['Reliance Industries', 'Adani Power', 'SAIL'],
    riskRatios: { sharpe: 1.75, alpha: 7.5, beta: 1.10, sortino: 2.0, standardDeviation: 17.5 },
    score: { total: 91, returns: 29, expense: 12, manager: 14, volatility: 11, aum: 9, drawdown: 11, quality: 5 },
    description: 'Aggressive multi-cap fund using Quant’s proprietary VLRT framework.',
    redFlags: []
  }
];

export const CATEGORY_GUIDANCE = {
  // Equity
  'Small Cap': 'High risk, high reward. Invests in emerging companies. Minimum 7+ years horizon.',
  'Mid Cap': 'Balanced growth and volatility. Invests in future industry leaders.',
  'Large Cap': 'Relatively stable. Invests in top 100 established companies.',
  'Flexi Cap': 'Dynamic investment across all market caps based on market conditions.',
  'Multi Cap': 'Strict allocation across Small, Mid, and Large caps (25% each).',
  'ELSS': 'Tax-saving equity funds with a 3-year lock-in under Section 80C.',
  'Focused': 'Concentrated portfolio of max 30 stocks for high conviction growth.',
  'Sectoral': 'Targeted investment in specific industries like Banking, Tech, or Pharma.',
  
  // Hybrid
  'Aggressive Hybrid': 'Mix of 65-80% Equity and rest in Debt for capital appreciation.',
  'Balanced Advantage': 'Dynamic Asset Allocation that shifts between Debt and Equity.',
  'Arbitrage': 'Low risk. Profits from price differences in cash and derivatives markets.',
  'Multi Asset': 'Invests in at least 3 asset classes (Equity, Debt, Gold).',

  // Debt
  'Liquid': 'Safe for 1-90 days. Ideal for parking emergency funds.',
  'Ultra Short': 'Low risk for 3-6 months. Better than savings bank returns.',
  'Corporate Bond': 'Invests in high-rated corporate papers for steady income.',
  'Gilt': 'Invests in Government Securities. Sensitive to interest rate changes.',
  'Overnight': 'Extremely safe. Invests in securities maturing in 1 day.',

  // Others
  'Index Fund': 'Passive low-cost funds that track indices like Nifty 50 or Sensex.',
  'ETF': 'Exchange Traded Funds. Passive, low cost, and traded like stocks.',
  'International': 'Provides exposure to global markets like US, China, or Europe.'
};
